name: CI Test

on:
  workflow_dispatch:

env:
  UV_VERSION: "0.4.29"

jobs:
  linter_tester:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.13]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      AGENTS_LLM_CONFIG_FILE_REF_KEY: litellm
      AGENTS_LLM_CONFIG_FILE: agents_llm_config.json
      HERCULES_CI_LITELLM_API_KEY: ${{ secrets.HERCULES_CI_LITELLM_API_KEY }}
      HERCULES_CI_LITELLM_BASE_URL: ${{ secrets.HERCULES_CI_LITELLM_BASE_URL }}
      HERCULES_CI_LITELLM_MODEL_NAME: ${{ vars.HERCULES_CI_LITELLM_MODEL_NAME }}
      HERCULES_CI_LITELLM_MAX_TOKENS: ${{ vars.HERCULES_CI_LITELLM_MAX_TOKENS }}
      GEO_API_KEY: ${{ secrets.GEO_API_KEY }}
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python 
      ENABLE_TELEMETRY: 0
      AUTO_MODE: 1
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
        id: setup_python
      # UV cache depends on OS, Python version and UV version.
      - name: Cache UV cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.UV_VERSION }}
      # virtualenv cache should depends on OS, Python version and `uv.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v5
        with:
          path: ~/.local
          key: uv-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install UV ${{ env.UV_VERSION }}
        run: |
          pip install uv==${{ env.UV_VERSION }}
      - name: Install project
        run: make install-extra
      - name: Run linter
        run: make lint
      - name: Write LiteLLM agents config
        run: |
          ./helper_scripts/write_litellm_config.py "$AGENTS_LLM_CONFIG_FILE"
      - name: Run tests
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          make test
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}
